name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run | tee cypress-output.log

      - name: Count total test cases
        run: |
          echo "Total test cases:"
          grep -Eo '[0-9]+ passing' cypress-output.log | grep -Eo '[0-9]+' || echo "0"
